### ISSUE TITLE
Make auto-join-raids setting default on/off per server

### ISSUE THREAD

**Issue by dragonslife** [PokeNavBot/PokeNav#146]
If possible, create a server setting that allows servers to set the default setting for auto-join-raids on or off per server. 

Otherwise maybe create a poll (Via Discord or stawpoll?) to see how many users/servers would like the default setting to be changed to OFF

**Comment by fortepc** [comment]
I personally think that the default for this setting should be on.

However, depending on how a server implements PokeNav specifically, it would be a good thing to have as a server level setting.

**Comment by dragonslife** [comment]
I can provide you with an answer on this: 

With the Pokémon Go scanning maps being down and no map to see ongoing raids on, players in our town are going around town to report all the ongoing raids they see in Discord. This doesn't necessarily mean that those players will actually participate in the raid as well. They're just going around checking for ongoing raids and reporting them to Discord, so other people who may be interested will be informed about ongoing raids and perhaps could join to do them.

**Comment by fortepc** [comment]
the users that are going around scouting raids actively are definitely the minority. So it seems to me that it being an opt-out feature still makes the most sense. Because a majority of users are just going to report the ones that they happen to be around anyway, or the ones that they actively want to do.

With how simple it is for a user to turn off auto join I think that the majority of the Casual users, which are the majority of users that you want to appeal to, would want to automatically be added to a raid they create. especially since only they or a raid moderator will be able to update the raid.

**Comment by fortepc** [comment]
I definitely see that my most active users turn auto join off, but the users who are the most casual who are the least likely to know how to turn it on are the ones who needed on the most. Whereas the most active users are the ones who are most likely to know how to turn it off are the ones who want to turn it off.

**Comment by fortepc** [comment]
It's one of those things where are user being active enough to be annoyed by this is in such a minority, and the fact that the users who are active enough to be annoyed by this are usually familiar enough with the bot to be able to know to turn it off.

Maybe the issue is with education. Maybe pokenav needs a tutorial like Meowth does Ware pokenav will walk you through all of the different settings that it has the ability to send for you and have you sent them

**Comment by dandesousa** [comment]
This will have a solution in the next update
